kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: whmall-dev
networking:
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/whmall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/whmall/deploy/config

- role: worker
  image: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/whmall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/whmall/deploy/config

- role: worker
  image: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/whmall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/whmall/deploy/config